// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBepx7cRQJyKfXgj_z3HC3hWEv1pgpGF5w',
    appId: '1:525781420854:web:8ceb9318118feafc020197',
    messagingSenderId: '525781420854',
    projectId: 'loginorregister-f2f54',
    authDomain: 'loginorregister-f2f54.firebaseapp.com',
    storageBucket: 'loginorregister-f2f54.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSUMBEYE3tk7-tu7ROW_VPnhNeOGDqRng',
    appId: '1:525781420854:android:cc47c8a8a03ddb59020197',
    messagingSenderId: '525781420854',
    projectId: 'loginorregister-f2f54',
    storageBucket: 'loginorregister-f2f54.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6DRm3f4O0klT-jWwQkNwyDA5YJuN5jrA',
    appId: '1:525781420854:ios:cc44ba4902466e46020197',
    messagingSenderId: '525781420854',
    projectId: 'loginorregister-f2f54',
    storageBucket: 'loginorregister-f2f54.firebasestorage.app',
    iosBundleId: 'com.example.loginorregister',
  );
}
